apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rhdhpai802-4
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rh-ee-lyoon/rhdhpai802-4:f898214f526beb93088d003386db39b4a84a9c3b@sha256:041550b2a138dbead96175437f4615420caea8fd823aee80b6fad51dd2ffdea7 # use pre-built to bootstrap
          name: app-inference
